### ISSUE TITLE
Problems with dependencies

### ISSUE THREAD

**Issue by kierancassel** [samdobson/monzo-coffee#13]
Trying to get this working, after failing to do it the Heroku one-click way I tried manually doing it, starting with "pipenv install".

```
root in monzo-coffee at muadness on  master
➜ pipenv install
Installing dependencies from Pipfile.lock (670b6f)...
An error occurred while installing sphinx-autobuild==0.7.1 --hash=sha256:66388f81884666e3821edbe05dd53a0cfb68093873d17320d0610de8db28c74e --hash=sha256:e60aea0789cab02fa32ee63c7acae5ef41c06f1434d9fd0a74250a61f5994692! Will try again.
An error occurred while installing -e git+git://github.com/samdobson/monzo-python.git@5873d452b19f31087d8d186f8103a3d87731bf37#egg=monzo-python!
Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 37/37 — 00:00:05
Installing initially failed dependencies...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

Then, I used "pipenv shell" to activate the pipenv.

And then I get this at the "python manage.py migrate" stage:

```
root in monzo-coffee at muadness on  master via monzo-coffee-FQAyL1Gz
➜ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/.local/share/virtualenvs/monzo-coffee-FQAyL1Gz/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/monzo-coffee/monzocoffee/urls.py", line 8, in <module>
    from hello import views
  File "/root/monzo-coffee/hello/views.py", line 12, in <module>
    from monzo.monzo import Monzo
ModuleNotFoundError: No module named 'monzo'
```

Presumably, something has gone wrong in the "pipenv install" stage but I am not well versed in Python and pipenv.

**Comment by samdobson** [comment]
Hey, thanks for the heads up. This has now been fixed with 0a28a8cd23e028b29412e1c1f3420dd6bd39d663
